fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_grub:
      repo: puppet/augeasproviders_grub
