---
.github/workflows/ci.yaml:
  acceptance_matrix: false
#      set:
#        - centos-7
#        - rocky-8
#      puppet:
#        - puppet5
#        - puppet6
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
