HOSTS:
  centos-7:
    roles:
      - client
      - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: vagrant
    vagrant_memsize: 1024
  centos-6:
    roles:
      - client
    platform: el-6-x86_64
    box: centos/6
    hypervisor: vagrant
    vagrant_memsize: 1024
CONFIG:
  type: aio
  log_level: verbose
